version: '3.9'
services:
  redis:
    image: redis:alpine
    restart: always
    command: redis-server --maxmemory 100mb --save "" --appendonly no --bind 127.0.0.1
    network_mode: host
  namizun: &ref
    image: s4l3h1/namizun:ubuntu-20.04
    build: .
    network_mode: host
  uploader:
    <<: *ref
    restart: always
    command: python3 uploader.py
